### ISSUE TITLE
Opening files does not work

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#1]
I understand that many buttons and menu entries are still stubs, but I think opening files is supposed to work. But if I try to use one of the menu entries for opening files, nothing happens if I select a valid media file.

The only way I could get it to play anything was loading a playlist and then double-clicking a playlist entry.

Tried this with git head and Qt 5.5.1.

**Comment by cmdrkotori** [comment]
This is an oversight on my part. Should be fixed by 6c68cb79.

**Comment by wm4** [comment]
Sorry, still doesn't work for me as of f145e39f15dbd78ded4f4272eb4db8fe41e89bae. Same behavior. Clicking the menu entry makes a file dialog show up, but selecting a file does nothing. Double-guessing from the commit message: the playlist wasn't hidden, and the "quick playlist" was selected.

**Comment by cmdrkotori** [comment]
What is your distro? I'll try to reproduce this on my end.

**Comment by wm4** [comment]
I tried on Debian unstable.

**Comment by cmdrkotori** [comment]
Opening from the menu appears to work in my vm.
[screenshot](https://a.pomf.cat/lffowz.png)

What's going on here, is that opening files uses a custom class called AsyncFileDialog (AFD) which creates a file dialog without spinning up a temporary event queue. It does this by tying itself to the dialog's lifespan and throwing itself away when the dialog is closed. It's not *really* necessary, except I found that using the static members of QFileDialog would sometimes not open the dialog at all and refuse to shut down normally. (This may be one or two Ubuntu versions ago.) In any case AFD seemed to fix it. However, this may not be compatible with QFileDialog going forward.

Points of failure in AFD for opening files are:
* not getting the right signal from QFileDialog (194:helpers.cpp)
* not getting a suitable file (urls.isEmpty() at 254:helpers.cpp)
* bad AFD mode set, and the calling class is listening to the wrong signal (264:helpers.cpp)

I will reintroduce the code and see if that fixes it. For now though, I need sleep.

**Comment by cmdrkotori** [comment]
Please check out the `dialog-refactor` branch and see if this fixes it for you.

**Comment by wm4** [comment]
It works.

**Comment by cmdrkotori** [comment]
Sounds good. I'll merge this into mainline.

**Comment by wm4** [comment]
How would you prefer should I report other issues? There's a lot of stuff stubbed out; I doubt you want a report for each of those.

**Comment by cmdrkotori** [comment]
Submitting this way is fine. If someone wants to request something that satisfies a personal itch, feel free to do so. Stuff like "please implement X in Y section, because I really want to do A while I do B" should be ok.

>There's a lot of stuff stubbed out; I doubt you want a report for each of those.

Yes, this bugs me too. Working out my entire entire gui before I'm prepared to implement it is a bad habit I picked up from developing with Borland C++ Builder years ago, where the tab order came from the order that the widgets were added. I actually don't like developing in a top-down fashion, because everything looks bad until right at the end.
