### ISSUE TITLE
why are external sub files added to playlist?

### ISSUE THREAD

**Issue by ahjolinna** [cmdrkotori/mpc-qt#174]
when I open a folder (with mpc-qt) that includes sub-directory which has external subtitle files mpc-qt adds them to the playlist and then it won't load them, but if the sub files are along side the video file (instead inside a sub-directory) then it does load the subtitle but it does still add them to the playlist.

if I try to open the video file directory from mpc-qt directly it just ignores the sub-folder

here is my gdb log output: [link ](https://gist.githubusercontent.com/ahjolinna/a8cb009647c6ffe9f8f4598ed67df1cb/raw/82351f8106a1d1b05de7c243ab82aa5c8cfd3be1/gistfile1.txt)

and I am using the latest mpv-full-git and ffmpeg-full-git and mpc-qt-git

---------

PS. small side question? is there a reason why the playlist changes the name from "file name" to "file title" when you have play(ed) it ...this is really noticeable if the names are 100% different

also have you heard about this project? : [QtMvvm](https://skycoder42.github.io/QtMvvm/)

**Comment by cmdrkotori** [comment]
I don't discriminate. Put it this way, the mime types that mpv accepts are a mile long and tracking down all the extensions feels like a chore. I might just steal the list from https://github.com/rossy/mpv-install/blob/master/mpv-install.bat

Haven't heard of QtMvvm. Looks neat tho.

**Comment by cmdrkotori** [comment]
Fixed in 50c477bc7772c47ee3cbbef2ea64322acf7ec133.

**Comment by ahjolinna** [comment]
well not fixed...
1 when I try to open the directory from mpc-qt it crashes; [logs](https://gist.githubusercontent.com/ahjolinna/03d79b0cfbaa5575854221dad06c7b08/raw/39927d27f2f49a42f66b44a0166e4a9b1cac6d16/gistfile1.txt)

2 it doesn't resolve the issue if choose from dolphin to open a folder with mpc-qt, it still adds those sub files.

what I like to happen is that mpc-qt would load the sub file normally but not put/add them to the playlist where it can't load them

....and small reminder this is only a problem if the sub files are are in a separate sub-directory. So either mpc-qt shouldn't add the stuff in the sub-directory (and just have them be added manually) or find away to load/add them in the proper way.

PS. I haven't checked if this affects external audio files, but I would assume it does (but you can play them). Also usually these external sub & audio files are using the same file name as the video, some video player (at least proprietary) like on PlayStation adds these sub/audio files automatically to the video if the file name matches

**Comment by cmdrkotori** [comment]
Ah, I forgot that files also read in through ipc. I'll get to that in a moment.

It's interesting, directories as playlist entires are expanded by mpv verbatim when played, which introduces files which are not playable including subtitle files. So I may have to expand directories myself. This may introduce freezes on very large filesystem structures. I'll try to push a partially working fix for this soon.

mpv grabbing nearby subs is a slightly different issue.

**Comment by cmdrkotori** [comment]
Having a great amount of unplayable items should be fixed now. It's not perfect however, because if we try to playback something the code expands to nothing, we aren't remove it like we should. It's harmless tho.

**Comment by ahjolinna** [comment]
@cmdrkotori : thanks that worked, okay it doesn't load the sub files automatically ....but I'm fine with that as I rather do that manually than have this playlist problem.

btw. I like to remind you about [Clazy](https://github.com/KDE/clazy) the Qt oriented code checker from KDE
