### ISSUE TITLE
Some sort of quick search in the playlist

### ISSUE THREAD

**Issue by wm4** [cmdrkotori/mpc-qt#4]
This is a feature request. It would be nice if there were a way to search in playlists. I imagine the following: press a certain key (xmms used 'J'), and a text box appears. Entering space-separated keywords filters out entries that don't match. Activating an entry will make search disappear and jump to the entry on the actual playlist.

**Comment by cmdrkotori** [comment]
Fixed in master.  I used ctrl+f as the default shortcut for revealing the search window; it can be remapped to J in the settings dialog if you like.

**Comment by wm4** [comment]
Not quite what I hoped it to be:
- it merely highlights matching entries on the playlist, which is pretty useless on a huge playlist (I'd expect it to filter the playlist as you type instead)
- can't scroll without the search closing
- search is case-sensitive
- it doesn't really match sub strings (e.g. for "Foo Bar Band" I'd expect "ban foo" to match)

Navigating the playlist should probably work normally, even while the search is active.

Additionally would be nice to have:
- ability to queue playlist entries while in the search
- closing the search with ESC

**Comment by cmdrkotori** [comment]
I see. To filter items instead of marking, the playlist window has to be decoupled from the model to some extent. I will do some guru meditation on the right way to do this. It may be easier than I suspect.

With respect to unable to scroll, I'll change the way search is closed to ESC as you suggest. I didn't think that would happen because usually X lets you scroll without changing focus, so I didn't test for it.

The other issues can be fixed by making the parser more robust.

Please wait warmly.

**Comment by wm4** [comment]
Looks pretty good already. Things I still have to point out (sorry):
- ESC resets the playlist scroll position to the top. It should go back to the old position instead.
- Arrow up/down should change the focused item playlist even during search, even if the keyboard focus is on the edit field.
- The playlist should keep the focused item if search mode is entered. If the search hides the currently focused item, the first match should be focused instead. If search is exited without selecting anything, the old focus should be restored; if something is selected, the new item should be focused.
- Enter during search (and if focus is on the edit field) should jump to the currently focused playlist item.

(Sorry for these overly specific demands... tell me when to stop.)

**Comment by cmdrkotori** [comment]
Should be fixed in master.

>(Sorry for these overly specific demands... tell me when to stop.)

No, that's okay. These suggestions are very helpful.

**Comment by wm4** [comment]
Now it's perfect. Thank you very much.

Still some focus glitches though. Need to test this more to find out under which circumstances they happen.

**Comment by wm4** [comment]
> Still some focus glitches though. 

One thing I noticed:
- hit ctrl+f to bring up the search window
- hit ESC to hide it
- now one of those buttons is focused, instead of the playlist

It should focus back to the playlist.

Also, the tab order in this area is a bit weird.

**Comment by cmdrkotori** [comment]
Fixed the focus glitches in master and a throwaway branch.

**Comment by wm4** [comment]
Tried with master. It's better, but focus still doesn't go back to the playlist.

**Comment by cmdrkotori** [comment]
Ah, shoot.

**Comment by cmdrkotori** [comment]
Should be fixed now.

**Comment by wm4** [comment]
Thanks.

I'm noticing that if you:
- hit ctrl+f
- enter something that would put you somewhere else on the playlist
- hit ESC without starting playback

That the selection is on the highlighted entry during search, instead of jumping back to the state before search. Not sure if that's a regression, or if such behavior was never intended anyway.
